ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ dev.roasti.ApplicationKt.module ]
    }
}

database {
    url = "jdbc:h2:mem:test;DB_CLOSE_DELAY=-1"
    url = ${?DATABASE_URL}
    driver = "org.h2.Driver"
}

uploads {
    dir = "./uploads"
    dir = ${?UPLOADS_DIR}
}

firebase {
    apiKey = ${?FIREBASE_API_KEY}
    credentialsBase64 = ${?FIREBASE_CREDENTIALS_JSON_BASE64}
    projectId = ${?FIREBASE_PROJECT_ID}
    identityBaseUrl = "https://identitytoolkit.googleapis.com/v1/accounts"
    identityBaseUrl = ${?FIREBASE_IDENTITY_BASE_URL}
    tokenBaseUrl = "https://securetoken.googleapis.com/v1/token"
    tokenBaseUrl = ${?FIREBASE_TOKEN_BASE_URL}
}
